# -*- coding: utf-8 -*-
"""CT-UTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cc695yG7V4NqoYBxKRsPdsIvj-rTjPh4
"""

# Import bisa disini


# Buat function hitung_mean
import os


def hitung_mean(data):
    # Jumlah semua data
    total = sum(data)
    mean = total / len(data)
    print(f"data = {data}")
    print(f"Rata-Ratanya adalah : {mean}")
    return mean  # Masukkan rumus menghitung Mean


# Buat function hitung median


def hitung_median(data):
    # Mengurutkan data
    data.sort()

    # Jika jumlah data genap
    if len(data) % 2 == 0:
        # Mengambil dua nilai tengah
        median1 = data[len(data) // 2]
        median2 = data[len(data) // 2 - 1]
        # Menghitung rata-rata dari dua nilai tengah
        median = (median1 + median2) / 2
    else:
        # Jika jumlah data ganjil, ambil nilai tengah langsung
        median = data[len(data) // 2]

    # Mencetak nilai median
    print(f"data = {data}")
    print("Median dari data adalah : ", median)

    # Mengembalikan nilai median
    return median


# Buat function hitung Kuartil


def hitung_kuartil(data):
    # Mengurutkan data
    data.sort()

    # Menghitung posisi kuartil
    Q1_pos = 1 + (len(data) - 1) * 0.25
    Q2_pos = 1 + (len(data) - 1) * 0.5
    Q3_pos = 1 + (len(data) - 1) * 0.75

    # Mengambil nilai kuartil
    Q1 = data[int(Q1_pos) - 1] + (Q1_pos - int(Q1_pos)) * (
        data[int(Q1_pos)] - data[int(Q1_pos) - 1]
    )
    Q2 = data[int(Q2_pos) - 1] + (Q2_pos - int(Q2_pos)) * (
        data[int(Q2_pos)] - data[int(Q2_pos) - 1]
    )
    Q3 = data[int(Q3_pos) - 1] + (Q3_pos - int(Q3_pos)) * (
        data[int(Q3_pos)] - data[int(Q3_pos) - 1]
    )

    # Mencetak nilai kuartil
    print("Kuartil pertama (Q1) dari data adalah : ", Q1)
    print("Kuartil kedua (Q2) atau median dari data adalah : ", Q2)
    print("Kuartil ketiga (Q3) dari data adalah : ", Q3)

    # Mengembalikan nilai kuartil
    return Q1, Q2, Q3


# Buat function hitung Modus


def hitung_modus(data):
    frekuensi = {}

    for elemen in data:
        if elemen in frekuensi:
            frekuensi[elemen] += 1
        else:
            frekuensi[elemen] = 1

    modus = []
    max_frekuensi = max(frekuensi.values())

    for k, v in frekuensi.items():
        if v == max_frekuensi:
            modus.append(k)

    # Mencetak nilai modus
    print(f"data = {data}")
    print("Modus dari data adalah : ", modus)

    return modus


# Buat function hitung Persentil


def hitung_persentil(data, P):
    # Mengurutkan data
    data.sort()

    # Menghitung posisi persentil
    n = len(data)
    pos = P * (n + 1) / 100

    # Jika posisi persentil adalah bilangan bulat
    if pos.is_integer():
        persentil = data[int(pos) - 1]
    else:
        # Jika posisi persentil bukan bilangan bulat
        persentil = data[int(pos) - 1] + (pos - int(pos)) * (
            data[int(pos)] - data[int(pos) - 1]
        )

    # Mencetak nilai persentil
    print("Persentil ke-", P, "dari data adalah : ", persentil)

    return persentil


# Buat function hitung Desil


def hitung_desil(data, jml_data):
    data_terurut = sorted(data)
    indeks_desil = (jml_data / 10) * len(data_terurut)
    if indeks_desil.is_integer():
        desil = (
            data_terurut[int(indeks_desil)] + data_terurut[int(indeks_desil) - 1]
        ) / 2
    else:
        desil = data_terurut[int(indeks_desil)]

    # Mencetak nilai Desil
    print(f"data = {data}")
    print(f"Desil ke-{jml_data} dari data adalah : {desil}")

    return desil


# Buat function hitung Jangkauan


def hitung_jangkauan(data):
    # Mengurutkan data
    data.sort()

    # Menghitung jangkauan
    jangkauan = data[-1] - data[0]

    # Mencetak nilai jangkauan
    print(f"data = {data}")
    print("Jangkauan dari data adalah : ", jangkauan)

    return jangkauan


# Buat tampilan pilih menu


def menu_data_tunggal():
    os.system("clear")
    print("\n----------------")
    print("| Data Tunggal |")
    print("----------------\n")

    # Buat inputan jumlah data
    jml_data = int(input("Berapa jumlah data yang akan dimasukan : "))
    # Buat inputan user
    deret = input("Masukan deret bilangan : ")
    # Buat array untuk menyimpan inputan
    data = []
    for bilangan in deret.split(","):
        data.append(bilangan)

    data = [int(x) for x in data]
    os.system("clear")
    while True:
        print(f"\n{data} \n")
        userInput = int(
            input(
                "\nDashboard : \n\n1. Menghitung Mean\n2. Mencari Median\n3. Menghitung Modus\n4. Menghitung Kuartil\n5. Menghitung Desil\n6. Menghitung Persentil\n7. Menghitung Jangkauan\n\n9. Exit\n\nMasukkan pilihan nomor : "
            )
        )

        match userInput:
            case 1:
                hitung_mean(data)
            case 2:
                hitung_median(data)
            case 3:
                hitung_modus(data)
            case 4:
                hitung_kuartil(data)
            case 5:
                D = int(input("Masukkan nilai D untuk desil yang ingin dihitung : "))
                hitung_desil(data, D)
            case 6:
                P = int(
                    input("Masukkan nilai P untuk persentil yang ingin dihitung : ")
                )
                hitung_persentil(data, P)
            case 7:
                hitung_jangkauan(data)
            case 9:
                os.system("clear")
                print("\nTerima kasih\n")
                break
            case _:
                print("Menu tidak tersedia. silahkan masukan nomor yang tersedia!")


def menu_data_kelompok():
    os.system("clear")

    print("\n----------------")
    print("| Data Kelompok |")
    print("----------------\n")
    # Buat inputan jumlah data
    jml_data = int(input("Berapa jumlah data yang akan dimasukan : "))
    # Buat inputan user
    deret = input("Masukan deret bilangan : ")
    # Buat array untuk menyimpan inputan
    data = []
    for bilangan in deret.split(","):
        data.append(bilangan)

    data = [int(x) for x in data]

    while True:
        os.system("clear")
        print(f"| {data} |\n")
        userInput = int(
            input(
                "\nDashboard : \n\n1. Menghitung Mean\n2. Mencari Median\n3. Menghitung Modus\n4. Menghitung Kuartil\n5. Menghitung Desil\n6. Menghitung Persentil\n7. Menghitung Jangkauan\n\n9. Exit\n\nMasukkan pilihan nomor : "
            )
        )

        match userInput:
            case 1:
                hitung_mean(data)
            case 2:
                hitung_median(data)
            case 3:
                hitung_modus(data)
            case 4:
                hitung_kuartil(data)
            case 5:
                D = int(input("Masukkan nilai D untuk desil yang ingin dihitung : "))
                hitung_desil(data, D)
            case 6:
                P = int(
                    input("Masukkan nilai P untuk persentil yang ingin dihitung : ")
                )
                hitung_persentil(data, P)
            case 7:
                hitung_jangkauan(data)
            case 9:
                exit()


# Landing page
plh_menu = int(input("Menu: \n\n1. Data Tunggal\n2. Data Kelompok \n\n Pilih menu: "))
match plh_menu:
    case 1:
        menu_data_tunggal()
    case 2:
        menu_data_kelompok()
    case _:
        print("Menu tidak tersedia. masukan angka 1 / 2")
